# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_token_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='uid',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
